#!/usr/bin/env bash
# Configures load balancer

config='\nfrontend web_front
\n\tbind *:80
\n\tmode http
\n\tdefault_backend web_back
\n
\nbackend web_back
\n\tbalance roundrobin
\n\tserver 304-web-01 35.229.29.70:80 check
\n\tserver 304-web-02 34.73.99.240:80 check\n'

# installation
apt-get -y update
apt-get -y install haproxy

# init script enabled
echo -e "ENABLED=0\nENABLED=1" >> /etc/default/haproxy

# roundrobin configuration
echo -e $config >> /etc/haproxy/haproxy.cfg

service haproxy restart
