#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
target=$(date +%d-%m-%Y).tar.gz
mysqldump -u root -p "$1" --opt --databases > backup.sql
tar -cfvz "$target" backup.sql
