#!/usr/bin/env bash
#displays the prase indefinitely and does not terminate on SIGTERM
i="1"
while ((i == 1))
do
      echo "To infinity and beyond"
      sleep 2
      trap "echo 'I am invincible!!!'" SIGTERM
done
