#!/usr/bin/env bash
i="1"
while ((i < 101))
do
	if ((i % 15 == 0))
	then
		echo "Fizzbuzz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	else
		echo $i
	fi
((i += 1))
done
