#!/usr/bin/env bash
#Prints Holberton school 10 times, with bad luck or good luck on lines 4 and 8
i="0"
while (( i < 10))
do
	if ((i == 3)); then echo bad luck
	elif ((i == 7)); then echo good luck
	else echo Holberton School; fi
	((i = i + 1))
done
