#!/usr/bin/env bash
# fixes server to run nginx as nginx user

# stop apache
pkill apache2

# make nginx user owner of nginx processes
sudo sed -i "1i user nginx;" /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf

# make sure nginx is listening on port 80
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default

# restart nginx
sudo -u nginx service nginx restart
